Updates to Cmake needed for tests

diff --git a/test/testPolarization.sh.in b/test/testPolarization.sh.in
--- a/test/testPolarization.sh.in
+++ b/test/testPolarization.sh.in
@@ -9,11 +9,11 @@ then
   exit 1;
 fi
 
-if [ ! -e testPolarization.cout ]
-then
-   echo "ERROR: testPolarization.cout does not exist"
-   exit 1;
-fi
+#if [ ! -e testPolarization.cout ]
+#then
+#   echo "ERROR: testPolarization.cout does not exist"
+#   exit 1;
+#fi
 
 OS=`uname`
 case "$OS" in
